server:
  applicationConnectors:
    - type: http
      port: 1337
  adminConnectors:
    - type: http
      port: 1338

document_root: "C:\\Users\\andy\\Documents\\projects\\thehardwareproject.org\\files"

logging:
  level: INFO

database:
  driverClass: com.mysql.jdbc.Driver
  user: dev
  password: dev
  url: jdbc:mysql://localhost:3306/laozi_server?useSSL=false
